/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as spermSol from "./sperm.sol";
export type { spermSol };
export type { SpermBank } from "./SpermBank";
export * as factories from "./factories";
export type { SpermBank } from "./sperm.sol/SpermBank";
export { SpermBank__factory } from "./factories/sperm.sol/SpermBank__factory";
