/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpermBank } from "./SpermBank";
export * as factories from "./factories";
export { SpermBank__factory } from "./factories/SpermBank__factory";
